"""A small distributed training (PyTorch DDP) to try `meshvpn launch` with.

It learns to classify points of a "spiral" dataset with a small MLP. Uses the GPUs if there are
any (NCCL), otherwise the CPUs (gloo) - so it runs on any group of nodes. Every node needs the
same code and the dataset (generated by prepare_data.py, or on the fly).

    # one machine, two processes:
    torchrun --standalone --nproc_per_node=2 train.py
    # many nodes through meshvpn (see run.sh and docs/distributed-training.md):
    meshvpn launch tag:gpu --workdir meshvpn-example -- ./run.sh
"""
import argparse
import os
import socket
import time

import torch
import torch.distributed as dist
import torch.nn as nn
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import DataLoader, DistributedSampler, TensorDataset

from prepare_data import spirals


def log(*args):
    # Only the first process of the job prints the progress; everyone prints errors.
    if int(os.environ.get("RANK", 0)) == 0:
        print(*args, flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="data/spirals.pt", help="dataset from prepare_data.py (generated if missing)")
    ap.add_argument("--epochs", type=int, default=10)
    ap.add_argument("--batch-size", type=int, default=256, help="per process")
    ap.add_argument("--lr", type=float, default=3e-3)
    ap.add_argument("--out", default="checkpoints", help="where rank 0 writes checkpoints")
    ap.add_argument("--resume", action="store_true", help="continue from the last checkpoint")
    args = ap.parse_args()

    # torchrun sets RANK, LOCAL_RANK, WORLD_SIZE, MASTER_ADDR, MASTER_PORT for every process.
    cuda = torch.cuda.is_available()
    dist.init_process_group("nccl" if cuda else "gloo")
    rank, world = dist.get_rank(), dist.get_world_size()
    local_rank = int(os.environ.get("LOCAL_RANK", 0))
    device = torch.device(f"cuda:{local_rank}" if cuda else "cpu")
    if cuda:
        torch.cuda.set_device(device)

    # Who takes part: every process reports its node.
    hosts = [None] * world
    dist.all_gather_object(hosts, f"{socket.gethostname()}/{device}")
    log(f"{world} processes on {len(set(h.split('/')[0] for h in hosts))} node(s): {', '.join(hosts)}")
    log(f"backend {dist.get_backend()}, rendezvous {os.environ.get('MASTER_ADDR')}:{os.environ.get('MASTER_PORT')}, "
        f"network {os.environ.get('MESHVPN_PATH', '-')} ({os.environ.get('NCCL_SOCKET_IFNAME', '-')})")

    if os.path.exists(args.data):
        x, y = torch.load(args.data, weights_only=True)
    else:
        x, y = spirals()  # the same on every node (fixed seed)
    split = int(len(x) * 0.9)
    train = TensorDataset(x[:split], y[:split])
    test_x, test_y = x[split:].to(device), y[split:].to(device)
    # Every process sees a different part of the data each epoch.
    sampler = DistributedSampler(train, num_replicas=world, rank=rank, shuffle=True, seed=0)
    loader = DataLoader(train, batch_size=args.batch_size, sampler=sampler)

    model = nn.Sequential(
        nn.Linear(2, 128), nn.ReLU(), nn.Linear(128, 128), nn.ReLU(), nn.Linear(128, 3)
    ).to(device)
    model = DDP(model, device_ids=[local_rank] if cuda else None)
    opt = torch.optim.AdamW(model.parameters(), lr=args.lr)

    start = 0
    ckpt = os.path.join(args.out, "last.pt")
    if args.resume and os.path.exists(ckpt):
        state = torch.load(ckpt, map_location=device, weights_only=True)
        model.module.load_state_dict(state["model"])
        opt.load_state_dict(state["opt"])
        start = state["epoch"] + 1
        log(f"resuming after epoch {state['epoch'] + 1}")

    for epoch in range(start, args.epochs):
        sampler.set_epoch(epoch)
        model.train()
        t0, seen, total_loss = time.time(), 0, 0.0
        for xb, yb in loader:
            xb, yb = xb.to(device), yb.to(device)
            loss = nn.functional.cross_entropy(model(xb), yb)
            opt.zero_grad()
            loss.backward()  # DDP averages the gradients of all processes here
            opt.step()
            seen += len(xb)
            total_loss += loss.item() * len(xb)
        # The loss and throughput of all processes together.
        stats = torch.tensor([total_loss, seen], device=device, dtype=torch.float64)
        dist.all_reduce(stats)
        model.eval()
        with torch.no_grad():
            acc = (model(test_x).argmax(1) == test_y).float().mean().item()
        secs = time.time() - t0
        log(f"epoch {epoch + 1}/{args.epochs}: loss {stats[0] / stats[1]:.4f}, test accuracy {acc:.1%}, "
            f"{stats[1] / secs:,.0f} samples/s")
        if rank == 0:
            os.makedirs(args.out, exist_ok=True)
            torch.save({"model": model.module.state_dict(), "opt": opt.state_dict(), "epoch": epoch}, ckpt)

    log(f"done - checkpoint in {os.path.abspath(ckpt)} on {socket.gethostname()}")
    dist.destroy_process_group()


if __name__ == "__main__":
    main()
